services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=mypassword'
      - 'POSTGRES_USER=myusername'
    ports:
      - '5432:5432'
