package ru.rieksp.coreservice.exception

enum class ErrorCode {
    ENTITY_ALREADY_EXIST,
    ENTITY_NOT_FOUND,
    ACCESS_DENIED,
    INVALID_USER_STATUS,
    INVALID_PASSPORT_STATUS,
    INCOMPATIBLE_FILE_EXT,
    INCOMPATIBLE_FILE_SIZE,
    USER_DRAFT_STATUS,
    UNEXPECTED_EXCEPTION,
    AUTH_NOT_AVAILABLE,
    INVALID_AUTH_RESPONSE,
    PAYLOAD_NOT_READABLE,
    UNEXPECTED_FIELD_TYPE,
    TRY_TO_DELETE_DATA_MANAGER,
    TRY_TO_DELETE_DIV_MANAGER,
    PAYLOAD_NOT_VALID,
    FACT_PINNED_TO_ANOTHER_MODULE,
    URL_NOT_EXISTS,
    PASSPORT_ALREADY_EXIST,
    PASSPORT_NOT_DRAFT
}