package com.example.ConfigService.model.entity

data class FactEntity(val id: Int,
    val regionFk: Int,
    val dataSourceFk: Int,
    val factName: String,
    val measurementUnitId: Int,
    val measurementUnitName: String,
    val measurementUnitShortName: String,
    val goal: String? = null,
    val goalType: Int? = null,
    val highThreshold: Float? = null,
    val lowThreshold: Float? = null,
    val highThresholdPct: Float? = null,
    val lowThresholdPct: Float? = null,
    val normActFk : Int? = null,
    val normActName: String? = null,
    val actualSince: Long,
    val period: Int,
    val planLoadDays: Int,
    val factLoadDate: Long,
    val moduleId: Int? = null,
    val moduleName: String? = null,
    val respUserFk: Int? = null,
    val respUserName: String? = null,
    val respUserLastName: String? = null,
    val respUserMiddleName: String? = null,
    val respUserDivisionId: Int? = null,
    val respUserDivisionShortName: String? = null,
    val respUserDivisionFullName: String? = null,
    val regionName: String? = null)
