INSERT INTO regions(id, name) VALUES (1, 'Республика Адыгея (Адыгея)');
INSERT INTO regions(id, name) VALUES (2, 'Республика Башкортостан');
INSERT INTO regions(id, name) VALUES (3, 'Республика Бурятия');
INSERT INTO regions(id, name) VALUES (4, 'Республика Алтай');
INSERT INTO regions(id, name) VALUES (5, 'Республика Дагестан');
INSERT INTO regions(id, name) VALUES (6, 'Республика Ингушетия');
INSERT INTO regions(id, name) VALUES (7, 'Кабардино-Балкарская Республика');
INSERT INTO regions(id, name) VALUES (8, 'Республика Калмыкия');
INSERT INTO regions(id, name) VALUES (9, 'Карачаево-Черкесская Республика');
INSERT INTO regions(id, name) VALUES (10, 'Республика Карелия');
INSERT INTO regions(id, name) VALUES (11, 'Республика Коми');
INSERT INTO regions(id, name) VALUES (12, 'Республика Марий Эл');
INSERT INTO regions(id, name) VALUES (13, 'Республика Мордовия');
INSERT INTO regions(id, name) VALUES (14, 'Республика Саха (Якутия)');
INSERT INTO regions(id, name) VALUES (15, 'Республика Северная Осетия - Алания');
INSERT INTO regions(id, name) VALUES (16, 'Республика Татарстан (Татарстан)');
INSERT INTO regions(id, name) VALUES (17, 'Республика Тыва');
INSERT INTO regions(id, name) VALUES (18, 'Удмуртская Республика');
INSERT INTO regions(id, name) VALUES (19, 'Республика Хакасия');
INSERT INTO regions(id, name) VALUES (20, 'Чеченская Республика');
INSERT INTO regions(id, name) VALUES (21, 'Чувашская республика - Чувашия');
INSERT INTO regions(id, name) VALUES (22, 'Алтайский край');
INSERT INTO regions(id, name) VALUES (23, 'Краснодарский край');
INSERT INTO regions(id, name) VALUES (24, 'Красноярский край');
INSERT INTO regions(id, name) VALUES (25, 'Приморский край');
INSERT INTO regions(id, name) VALUES (26, 'Ставропольский край');
INSERT INTO regions(id, name) VALUES (27, 'Хабаровский край');
INSERT INTO regions(id, name) VALUES (28, 'Амурская область');
INSERT INTO regions(id, name) VALUES (29, 'Архангельская область');
INSERT INTO regions(id, name) VALUES (30, 'Астраханская область');
INSERT INTO regions(id, name) VALUES (31, 'Белгородская область');
INSERT INTO regions(id, name) VALUES (32, 'Брянская область');
INSERT INTO regions(id, name) VALUES (33, 'Владимирская область');
INSERT INTO regions(id, name) VALUES (34, 'Волгоградская область');
INSERT INTO regions(id, name) VALUES (35, 'Вологодская область');
INSERT INTO regions(id, name) VALUES (36, 'Воронежская область');
INSERT INTO regions(id, name) VALUES (37, 'Ивановская область');
INSERT INTO regions(id, name) VALUES (38, 'Иркутская область');
INSERT INTO regions(id, name) VALUES (39, 'Калининградская область');
INSERT INTO regions(id, name) VALUES (40, 'Калужская область');
INSERT INTO regions(id, name) VALUES (41, 'Камчатский край');
INSERT INTO regions(id, name) VALUES (42, 'Кемеровская область - Кузбасс');
INSERT INTO regions(id, name) VALUES (43, 'Кировская область');
INSERT INTO regions(id, name) VALUES (44, 'Костромская область');
INSERT INTO regions(id, name) VALUES (45, 'Курганская область');
INSERT INTO regions(id, name) VALUES (46, 'Курская область');
INSERT INTO regions(id, name) VALUES (47, 'Ленинградская область');
INSERT INTO regions(id, name) VALUES (48, 'Липецкая область');
INSERT INTO regions(id, name) VALUES (49, 'Магаданская область');
INSERT INTO regions(id, name) VALUES (50, 'Московская область');
INSERT INTO regions(id, name) VALUES (51, 'Мурманская область');
INSERT INTO regions(id, name) VALUES (52, 'Нижегородская область');
INSERT INTO regions(id, name) VALUES (53, 'Новгородская область');
INSERT INTO regions(id, name) VALUES (54, 'Новосибирская область');
INSERT INTO regions(id, name) VALUES (55, 'Омская область');
INSERT INTO regions(id, name) VALUES (56, 'Оренбургская область');
INSERT INTO regions(id, name) VALUES (57, 'Орловская область');
INSERT INTO regions(id, name) VALUES (58, 'Пензенская область');
INSERT INTO regions(id, name) VALUES (59, 'Пермский край');
INSERT INTO regions(id, name) VALUES (60, 'Псковская область');
INSERT INTO regions(id, name) VALUES (61, 'Ростовская область');
INSERT INTO regions(id, name) VALUES (62, 'Рязанская область');
INSERT INTO regions(id, name) VALUES (63, 'Самарская область');
INSERT INTO regions(id, name) VALUES (64, 'Саратовская область');
INSERT INTO regions(id, name) VALUES (65, 'Сахалинская область');
INSERT INTO regions(id, name) VALUES (66, 'Свердловская область');
INSERT INTO regions(id, name) VALUES (67, 'Смоленская область');
INSERT INTO regions(id, name) VALUES (68, 'Тамбовская область');
INSERT INTO regions(id, name) VALUES (69, 'Тверская область');
INSERT INTO regions(id, name) VALUES (70, 'Томская область');
INSERT INTO regions(id, name) VALUES (71, 'Тульская область');
INSERT INTO regions(id, name) VALUES (72, 'Тюменская область');
INSERT INTO regions(id, name) VALUES (73, 'Ульяновская область');
INSERT INTO regions(id, name) VALUES (74, 'Челябинская область');
INSERT INTO regions(id, name) VALUES (75, 'Забайкальский край');
INSERT INTO regions(id, name) VALUES (76, 'Ярославская область');
INSERT INTO regions(id, name) VALUES (77, 'Город Москва');
INSERT INTO regions(id, name) VALUES (78, 'Город Санкт-Петербург');
INSERT INTO regions(id, name) VALUES (79, 'Еврейская автономная область');
INSERT INTO regions(id, name) VALUES (83, 'Ненецкий автономный округ');
INSERT INTO regions(id, name) VALUES (86, 'Ханты-Мансийский автономный округ - Югра');
INSERT INTO regions(id, name) VALUES (87, 'Чукотский автономный округ');
INSERT INTO regions(id, name) VALUES (89, 'Ямало-Ненецкий автономный округ');
INSERT INTO regions(id, name) VALUES (90, 'Запорожская область');
INSERT INTO regions(id, name) VALUES (91, 'Республика Крым');
INSERT INTO regions(id, name) VALUES (92, 'Город Севастополь');
INSERT INTO regions(id, name) VALUES (93, 'Донецкая Народная Республика');
INSERT INTO regions(id, name) VALUES (94, 'Луганская Народная Республика');
INSERT INTO regions(id, name) VALUES (95, 'Херсонская область');
INSERT INTO regions(id, name) VALUES (99, 'Байконур и прочие территории');


INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10001, 67, null, 'Правительство Смоленской области', 'Правительство Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10002, 67, 10001, 'Аппарат Правительства Смоленской области', 'Аппарат Правительства Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10003, 67, 10002, '', 'Главное управление аналитической и проектной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10004, 67, 10003, '', 'Отдел сопровождения реализации национальных проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10005, 67, 10003, '', 'Отдел мониторинга реализации национальных проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10006, 67, 10003, '', 'Сектор методологии и обучения проектному управлению');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10007, 67, 10002, '', 'Главное правовое управление');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10008, 67, 10007, '', 'Отдел правовой экспертизы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10009, 67, 10007, '', 'Отдел лингвистической экспертизы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10010, 67, 10007, '', 'Отдел законопроектной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10011, 67, 10007, '', 'Отдел по осуществлению контрольных функций, вопросам помилования и организационной работе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10012, 67, 10007, '', 'Отдел правового мониторинга и судебной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10013, 67, 10002, '', 'Управление государственной гражданской службы и кадровой политики');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10014, 67, 10013, '', 'Отдел государственной гражданской службы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10015, 67, 10013, '', 'Отдел кадров');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10016, 67, 10013, '', 'Отдел государственных наград и геральдики');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10017, 67, 10002, '', 'Управление документооборота');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10018, 67, 10017, '', 'Отдел документационного обеспечения деятельности Губернатора Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10019, 67, 10017, '', 'Отдел учета и регистрации правовых актов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10020, 67, 10017, '', 'Сектор обработки корреспонденции и архивного дела');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10021, 67, 10002, '', 'Департамент по контролю');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10022, 67, 10021, '', 'Отдел контроля за исполнением поручений Губернатора Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10023, 67, 10021, '', 'Отдел контроля за исполнением поручений Президента Российской Федерации и Правительства Российской Федерации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10024, 67, 10002, '', 'Департамент протокола');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10025, 67, 10024, '', 'Отдел обеспечения проведения протокольных мероприятий');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10026, 67, 10024, '', 'Сектор планирования деятельности Правительства Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10027, 67, 10002, '', 'Финансовый департамент');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10028, 67, 10027, '', 'Отдел финансового учета и отчетности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10029, 67, 10027, '', 'Отдел материального учета и взаимодействия с подведомственными учреждениями');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10030, 67, 10002, '', 'Департамент по работе с обращениями граждан и организации оказания гражданам бесплатной юридической');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10031, 67, 10030, '', 'Отдел организации рассмотрения обращений граждан');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10032, 67, 10030, '', 'Сектор контроля за рассмотрением обращений граждан');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10033, 67, 10030, '', 'Отдел организации оказания гражданам бесплатной юридической помощи');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10034, 67, 10002, '', 'Департамент по мобилизационной подготовке');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10035, 67, 10002, '', 'Департамент по профилактике коррупционных правонарушений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10036, 67, 10035, '', 'Отдел антикоррупционных проверок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10037, 67, 10035, '', 'Отдел антикоррупционного мониторинга');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10038, 67, 10002, '', 'Департамент международных связей');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10039, 67, 10038, '', 'Отдел международных связей и приграничного сотрудничества');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10040, 67, 10038, '', 'Отдел межрегионального сотрудничества и внешних связей');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10041, 67, 10002, '', 'Отдел государственных закупок и информационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10042, 67, 10002, '', 'Отдел специальной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10043, 67, 10001, 'Представительство Правительства Смоленской области', 'Представительство Правительства Смоленской области при Правительстве Российской Федерации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10044, 67, 10001, 'Минфин Смоленской области', 'Министерство финансов Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10045, 67, 10044, '', 'Департамент казначейского исполнения бюджета');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10046, 67, 10045, '', 'Отдел исполнения бюджета по расходам');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10047, 67, 10045, '', 'Отдел операционно-кассового обслуживания');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10048, 67, 10044, '', 'Отдел автоматизированных систем управления бюджетным процессом');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10049, 67, 10044, '', 'Департамент планирования расходов отраслей непроизводственной сферы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10050, 67, 10049, '', 'Отдел планирования расходов отраслей социальной сферы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10051, 67, 10050, '', 'Сектор планирования расходов государственного аппарата');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10052, 67, 10044, '', 'Отдел бюджетного учёта и отчётности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10053, 67, 10044, '', 'Отдел правового, кадрового и организационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10054, 67, 10044, '', 'Департамент по межбюджетным отношениям и долговым обязательствам');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10055, 67, 10054, '', 'Отдел межбюджетных отношений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10056, 67, 10055, '', 'Сектор управления государственным долгом');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10057, 67, 10044, '', 'Департамент бюджетного планирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10058, 67, 10057, '', 'Отдел планирования расходов отраслей производственной сферы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10059, 67, 10057, '', 'Сводный бюджетный отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10060, 67, 10044, '', 'Отдел прогнозирования и анализа доходов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10061, 67, 10044, '', 'Отдел исполнения бюджета по средствам резервного фонда');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10062, 67, 10001, 'Министерство Смоленской области по внутренней политике', 'Министерство Смоленской области по внутренней политике');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10063, 67, 10062, '', 'Департамент юридической и финансовой работы   ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10064, 67, 10063, '', 'Отдел юридической работы и административно-территориального устройства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10065, 67, 10063, '', 'Отдел регистра муниципальных нормативных правовых актов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10066, 67, 10063, '', 'Отдел финансовой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10067, 67, 10062, '', 'Департамент пресс-службы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10068, 67, 10067, '', 'Отдел пресс-службы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10069, 67, 10067, '', 'Отдел по работе со средствами массовой информации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10070, 67, 10062, '', 'Департамент по взаимодействию с общественными объединениями');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10071, 67, 10070, '', 'Отдел по взаимодействию с общественными и религиозными организациями');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10072, 67, 10070, '', 'Сектор межнациональных и межконфессиональных отношений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10073, 67, 10062, '', 'Отдел аналитической работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10074, 67, 10062, '', 'Сектор по защите информации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10075, 67, 10062, '', 'Отдел муниципальной службы, мониторинга и содействия развитию  местного самоуправления');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10076, 67, 10062, '', 'Отдел по работе с муниципальными образованиями');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10077, 67, 10062, '', 'Отдел государственного заказа');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10078, 67, 10062, '', 'Отдел кадровой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10079, 67, 10062, '', 'Отдел по взаимодействию с политическими партиями');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10080, 67, 10001, 'Министерство Смоленской области по осуществлению контроля и взаимодействию с административными органами', 'Министерство Смоленской области по осуществлению контроля и взаимодействию с административными органами');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10081, 67, 10080, '', 'Департамент финансового обеспечения и правовой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10082, 67, 10081, '', 'Финансовый отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10083, 67, 10081, '', 'Отдел правового, кадрового обеспечения и взаимодействия с административными органами');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10084, 67, 10080, '', 'Департамент контроля в сфере закупок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10085, 67, 10084, '', 'Отдел контроля в сфере закупок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10086, 67, 10084, '', 'Отдел государственного финансового контроля в сфере закупок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10087, 67, 10080, '', 'Департамент финансового контроля');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10088, 67, 10087, '', 'Отдел государственного финансового контроля');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10089, 67, 10087, '', 'Отдел отчетности и контроля за расходованием средств резервного фонда');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10090, 67, 10001, 'Минимущества Смоленской области', 'Министерство имущественных и земельных отношений Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10091, 67, 10090, '', 'Департамент имущественных отношений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10092, 67, 10091, '', 'Отдел управления областным имуществом');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10093, 67, 10091, '', 'Отдел учета областного имущества');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10094, 67, 10091, '', 'Отдел безвозмездного пользования и арендных отношений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10095, 67, 10090, '', 'Департамент правового регулирования и бюджетного планирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10096, 67, 10095, '', 'Отдел бухгалтерского учета и государственных контрактов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10097, 67, 10095, '', 'Отдел правового обеспечения и кадровой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10098, 67, 10090, '', 'Департамент земельных отношений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10099, 67, 10098, '', 'Отдел по предоставлению земельных участков ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10100, 67, 10098, '', 'Отдел регулирования земельных отношений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10101, 67, 10001, 'Минэкономразвития Смоленской области', 'Министерство экономического развития Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10102, 67, 10101, '', 'Департамент социально-экономического прогнозирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10103, 67, 10102, '', 'Отдел финансового, кадрового и организационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10104, 67, 10102, '', 'Отдел анализа и прогнозирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10105, 67, 10101, '', 'Департамент мониторинга бизнес-климата');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10106, 67, 10105, '', 'Сектор координации совершенствования контрольно-надзорной деятельности и содействия развитию конкуренции');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10107, 67, 10105, '', 'Сектор оценки регулирующего воздействия');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10108, 67, 10105, '', 'Отдел государственно-частного партнёрства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10109, 67, 10105, '', 'Отдел государственных программ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10110, 67, 10001, 'Министерство инвестразвития Смоленской области', 'Министерство инвестиционного развития Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10111, 67, 10110, '', 'Отдел развития малого и среднего бизнеса');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10112, 67, 10110, '', 'Отдел финансовой поддержки субъектов малого и среднего предпринимательства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10113, 67, 10110, '', 'Департамент реализации инвестиционных проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10114, 67, 10113, '', 'Отдел инвестиционных проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10115, 67, 10113, '', 'Отдел государственной поддержки инвестиционной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10116, 67, 10110, '', 'Департамент аналитического сопровождения и организационного обеспечения деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10117, 67, 10116, '', 'Аналитический отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10118, 67, 10116, '', 'Отдел финансового и юридического обеспечения ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10119, 67, 10116, '', 'Сектор стратегических проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10120, 67, 10001, 'Минпромторг Смоленской области', 'Министерство промышленности и торговли Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10121, 67, 10120, '', 'Отдел индустриальных парков и особых экономических зон');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10122, 67, 10120, '', 'Отдел финансовой и организационно-правовой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10123, 67, 10120, '', 'Отдел потребительского рынка');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10124, 67, 10120, '', 'Отдел лицензирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10125, 67, 10120, '', 'Отдел промышленности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10126, 67, 10001, 'Минтранс Смоленской области', 'Министерство транспорта и дорожного хозяйства Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10127, 67, 10126, '', 'Отдел бухгалтерского учета, отчетности и планирования расходов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10128, 67, 10126, '', 'Отдел правового и организационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10129, 67, 10126, '', 'Отдел дорожного хозяйства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10130, 67, 10126, '', 'Отдел обеспечения деятельности дорожного фонда');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10131, 67, 10126, '', 'Отдел транспорта');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10132, 67, 10001, 'Минсоциразвития Смоленской области', 'Министерство социального развития Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10133, 67, 10132, '', 'Департамент правового обеспечения, кадровой работы и контрольной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10134, 67, 10133, '', 'Отдел кадровой и организационной работы департамента правового обеспечения, кадровой работы и контрольной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10135, 67, 10133, '', 'Отдел правового обеспечения департамента правового обеспечения, кадровой работы и контрольной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10136, 67, 10133, '', 'Отдел охраны труда департамента правового обеспечения, кадровой работы и контрольной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10137, 67, 10133, '', 'Отдел материально-технического обеспечения подведомственных организаций и контрольной деятельности департамента правового обеспечения, кадровой работы и контрольной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10138, 67, 10132, '', 'Отдел бухгалтерского учета и отчетности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10139, 67, 10132, '', 'Отдел финансово-экономического планирования и труда');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10140, 67, 10132, '', 'Отдел государственного заказа и договорной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10141, 67, 10132, '', 'Департамент социального обслуживания и демографических процессов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10142, 67, 10141, '', 'Отдел социального обслуживания граждан и работы с некоммерческими организациями департамента социального обслуживания и демографических процессов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10143, 67, 10141, '', 'Отдел по работе с ветеранами, инвалидами и взаимодействию с общественными организациями департамента социального обслуживания и демографических процессов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10144, 67, 10141, '', 'Отдел по организации социальной поддержки и социальному обслуживанию семьи и детей департамента социального обслуживания и демографических процессов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10145, 67, 10132, '', 'Департамент реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10146, 67, 10145, '', 'Отдел контроля за назначением социальных выплат департамента реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10147, 67, 10145, '', 'Отдел информационных технологий департамента реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10148, 67, 10145, '', 'Отдел жилищно-коммунальных субсидий и льгот департамента реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10149, 67, 10145, '', 'Отдел по оказанию адресной помощи департамента реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10150, 67, 10145, '', 'Отдел по работе с отдельными категориями граждан и жилищному обеспечению департамента реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10151, 67, 10145, '', 'Сектор дистанционного информирования граждан департамента реализации государственных гарантий социальной защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10152, 67, 10132, '', 'Хозяйственный отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10153, 67, 10132, '', 'Отдел социальной защиты населения в г. Смоленске');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10154, 67, 10132, '', 'Отдел социальной защиты населения в Вяземском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10155, 67, 10132, '', 'Сектор социальной защиты населения в Гагаринском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10156, 67, 10132, '', 'Отдел социальной защиты населения в Починковском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10157, 67, 10132, '', 'Отдел социальной защиты населения в Рославльском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10158, 67, 10132, '', 'Отдел социальной защиты населения в Руднянском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10159, 67, 10132, '', 'Отдел социальной защиты населения в Сафоновском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10160, 67, 10132, '', 'Отдел социальной защиты населения в Смоленском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10161, 67, 10132, '', 'Отдел социальной защиты населения в Ярцевском районе');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10162, 67, 10132, '', 'Отдел социальной защиты населения в г. Десногорске');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10163, 67, 10001, 'Минздрав Смоленской области', 'Министерство здравоохранения Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10164, 67, 10163, '', 'Департамент организации медицинской помощи населению');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10165, 67, 10164, '', 'Отдела организации медицинской помощи детям и службы родовспоможения департамента организации медицинской помощи населению');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10166, 67, 10164, '', 'Отдел организации стационарной, специализированной и высокотехнологичной медицинской помощи');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10167, 67, 10163, '', 'Департамента ведомственного контроля и лицензирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10168, 67, 10167, '', 'Отдела ведомственного контроля качества и безопасности медицинской деятельности департамента ведомственного контроля и лицензирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10169, 67, 10164, '', 'Отдела организации первичной медико-санитарной и скорой медицинской помощи департамента организации медицинской помощи населению');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10170, 67, 10163, '', 'Отдела кадров');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10171, 67, 10163, '', 'Отдела медицинского образования, развития медицинских кадров и волонтерства в здравоохранении');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10172, 67, 10163, '', 'Отдела правового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10173, 67, 10163, '', 'Отдела цифровизации процессов в здравоохранении');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10174, 67, 10163, '', 'Отдела бюджетного учёта и отчётности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10175, 67, 10163, '', 'Отдела реализации государственных программ и национальных проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10176, 67, 10163, '', 'Отдела материально-ресурсного обеспечения и формирования отраслевого государственного заказа');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10177, 67, 10163, '', 'Финансово-экономический отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10178, 67, 10163, '', 'Контрольно-ревизионный отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10179, 67, 10163, '', 'Отдел лекарственного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10180, 67, 10167, '', 'Отдел организационно-методической работы и лицензирования отдельных видов деятельности департамента ведомственного контроля и лицензирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10181, 67, 10180, '', 'Сектор лицензирования отдельных видов деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10182, 67, 10163, '', 'Отдел мобилизационного резерва');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10183, 67, 10001, 'Минобранауки Смоленской области', 'Министерство образования и науки Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10184, 67, 10183, '', 'Департамент правового и кадрового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10185, 67, 10184, '', 'Отдел правового и кадрового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10186, 67, 10185, '', 'Сектор организации деятельности комиссий по делам несовершеннолетних и защите их прав');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10187, 67, 10183, '', 'Департамент общего образования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10188, 67, 10187, '', 'Отдел дошкольного и общего образования ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10189, 67, 10188, '', 'Сектор образования детей с особыми образовательными потребностями');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10190, 67, 10183, '', 'Отдел воспитательной работы и отдыха');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10191, 67, 10190, '', 'Отдел опеки и попечительства ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10192, 67, 10183, '', 'Департамент среднего профессионального образования и науки');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10193, 67, 10192, '', 'Отдел профессионального образования и науки');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10194, 67, 10193, '', 'Отдел дополнительного образования и профориентационной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10195, 67, 10194, '', 'Сектор программно-проектной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10196, 67, 10183, '', 'Департамент по обеспечению деятельности образовательных организаций ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10197, 67, 10196, '', 'Отдел комплексного анализа и мониторинга');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10198, 67, 10197, '', 'Отдел эксплуатации зданий и сооружений и материального обеспечения подведомственных учреждений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10199, 67, 10183, '', 'Департамент экономического планирования и государственного заказа');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10200, 67, 10199, '', 'Отдел экономического планирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10201, 67, 10200, '', 'Отдел государственного заказа');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10202, 67, 10183, '', 'Департамент по надзору и контролю в сфере образования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10203, 67, 10202, '', 'Отдел государственного контроля (надзора) за соблюдением законодательства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10204, 67, 10203, '', 'Отдел государственных услуг');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10205, 67, 10204, '', 'Сектор информационно-аналитического сопровождения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10206, 67, 10001, 'Минкульт Смоленской области', 'Министерство культуры и туризма Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10207, 67, 10206, '', 'Отдел музеев и библиотечного дела');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10208, 67, 10206, '', 'Отдел туризма');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10209, 67, 10206, '', 'Отдел исполнительских искусств и развития сферы культуры');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10210, 67, 10206, '', 'Отдел архивного дела');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10211, 67, 10206, '', 'Отдел кадров, правовой работы и документооборота');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10212, 67, 10206, '', 'Отдел экономики, бюджетного учета и отчетности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10213, 67, 10001, 'Минцифры Смоленской области', 'Министерство цифрового развития Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10214, 67, 10213, '', 'Департамент развития цифровых сервисов и услуг');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10215, 67, 10213, '', 'Отдел развития инфраструктуры электронного правительства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10216, 67, 10213, '', 'Сектор совершенствования государственного управления');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10217, 67, 10213, '', 'Департамент цифровой трансформации и финансового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10218, 67, 10213, '', 'Отдел финансового и кадрового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10219, 67, 10213, '', 'Сектор аналитики и проектной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10220, 67, 10213, '', 'Отдел защиты информации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10221, 67, 10213, '', 'Отдел связи и телекоммуникационной инфраструктуры');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10222, 67, 10001, 'Минтруд Смоленской области', 'Министерство занятости населения и трудовой миграции Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10223, 67, 10222, '', 'Отдел специальных программ и трудовой миграции');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10224, 67, 10222, '', 'Отдел профориентации и профессионального обучения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10225, 67, 10222, '', 'Отдел программ занятости и мониторинга рынка труда');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10226, 67, 10222, '', 'Отдел правовой и кадровой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10227, 67, 10222, '', 'Отдел подведомственных учреждений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10228, 67, 10222, '', 'Отдел финансовго планирования, бухглалтерского учета и отчетности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10229, 67, 10222, '', 'Отдел информационных технологий и информации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10230, 67, 10001, 'Минсельхоз Смоленской области', 'Министерство сельского хозяйства и продовольствия Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10231, 67, 10230, '', 'Отдел экономики');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10232, 67, 10230, '', 'Отдел государственной поддержки агропромышленного комплекса');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10233, 67, 10230, '', 'Отдел пищевой промышленности и переработки ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10234, 67, 10230, '', 'Отдел малых форм хозяйствования и кооперации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10235, 67, 10230, '', 'Отдел растениеводства, плодородия и агротехнологий');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10236, 67, 10230, '', 'Отдел животноводства и племенной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10237, 67, 10230, '', 'Отдел развития сельских территорий');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10238, 67, 10230, '', 'Отдел мониторинга земель сельскохозяйственного назначения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10239, 67, 10230, '', 'Отдел бухгалтерского учета, отчетности и материального обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10240, 67, 10230, '', 'Отдел правового, кадрового обеспечения и делопроизводства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10241, 67, 10001, 'Минприроды Смоленской области', 'Министерство природных ресурсов и экологии Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10242, 67, 10241, '', 'Отдел финансового и организационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10243, 67, 10242, '', 'Сектор организационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10244, 67, 10241, '', 'Отдел регионального экологического надзора');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10245, 67, 10241, '', 'Отдел недропользования и экологической экспертизы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10246, 67, 10245, '', 'Сектор регионального геологического надзора');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10247, 67, 10241, '', 'Отдел водных ресурсов, обеспечения безопасности гидротехнических сооружений и организации строительства природоохранных объектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10248, 67, 10247, '', 'Сектор государственного учета и контроля радиоактивных веществ и радиоактивных отходов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10249, 67, 10241, '', 'Отдел охраны окружающей среды и регулирования деятельности по обращению с отходами');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10250, 67, 10001, 'Минлесхоз Смоленской области', 'Министерство лесного хозяйства и охраны объектов животного мира Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10251, 67, 10250, '', 'Отдел экономики и финансов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10252, 67, 10250, '', 'Отдел бухгалтерского учета и администрирования платежей');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10253, 67, 10250, '', 'Отдел организации лесопользования, учета лесного фонда и арендных отношений  ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10254, 67, 10250, '', 'Отдел государственного лесного реестра, земельных отношений и экспертизы проектов освоения лесов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10255, 67, 10250, '', 'Отдел лесовосстановления, охраны и защиты лесного фонда ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10256, 67, 10250, '', 'Отдел федерального государственного лесного и охотничьего надзора');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10257, 67, 10250, '', 'Отдел государственного учета, кадастра, контроля использования объектов животного мира и промышленного рыболовства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10258, 67, 10250, '', 'Отдел правового и кадрового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10259, 67, 10250, '', 'Сектор взаимодействия со средствами массовой информации и информационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10260, 67, 10250, '', 'Сектор хозяйственного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10261, 67, 10001, 'Минстрой Смоленской области', 'Министерство архитектуры и строительства Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10262, 67, 10261, '', 'Сводно-аналитический отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10263, 67, 10261, '', 'Отдел цифровизации и информационных систем ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10264, 67, 10261, '', 'Отдел форматирования комфортной городской среды');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10265, 67, 10261, '', 'Отдел градостроительства ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10266, 67, 10261, '', 'Отдел планировки и застройки территории');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10267, 67, 10261, '', 'Сектор контроля за градостроительной деятельностью');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10268, 67, 10261, '', 'Отдел правового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10269, 67, 10261, '', 'Отдел бухгалтерского учета, отчетсности и планирования расходов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10270, 67, 10261, '', 'Сектор специальной работы ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10271, 67, 10261, '', 'Отдел развития жилищного строительства ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10272, 67, 10261, '', 'Отдел строительства социально-культурных объектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10273, 67, 10261, '', 'Отдел взаимодействия со строительным комплексом ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10274, 67, 10261, '', 'Отдел инфраструктурных проектов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10275, 67, 10261, '', 'Отдел ценообразования и сметного нормирования');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10276, 67, 10261, '', 'Сектор экономического анализа');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10277, 67, 10001, 'МинЖКХ Смоленской области', 'Министерство жилищно-коммунального хозяйства, энергетики и тарифной политики Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10278, 67, 10277, '', 'Отдел топливно-энергетического комплекса              ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10279, 67, 10277, '', 'Отдел технической экспертизы и энергетических балансов             ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10280, 67, 10277, '', 'Отдел по утверждению нормативов потребления коммунальных услуг и платы за технологическое присоединение            ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10281, 67, 10277, '', 'Отдел ценового регулирования энергоснабжающих организаций           ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10282, 67, 10277, '', 'Отдел ценового регулирования ресурсоснабжающих организаций          ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10283, 67, 10277, '', 'Отдел контрольно-аналитической работы        ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10284, 67, 10277, '', 'Отдел бухгалтерского учета, отчетности и планирования расходов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10285, 67, 10277, '', 'Отдел инженерной инфраструктуры и инвестиционных программ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10286, 67, 10277, '', 'Отдел жилищной политики');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10287, 67, 10277, '', 'Отдел развития коммунального хозяйства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10288, 67, 10001, 'Минспорт Смоленской области', 'Министерство спорта Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10289, 67, 10288, '', 'Отдел развития спорта, программ и проектной деятельности');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10290, 67, 10288, '', 'Отдел правового обеспечения и организации работы спортивных учреждений');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10291, 67, 10288, '', 'Отдел финансово-экономический');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10292, 67, 10001, 'Главное управление государственного строительного и технического надзора Смоленской области', 'Главное управление государственного строительного и технического надзора Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10293, 67, 10292, '', 'Отдел бухгалтерского учета и закупок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10294, 67, 10292, '', 'Отдел информационно-правовой и кадровой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10295, 67, 10001, 'Главное управление Смоленской области по регулированию контрактной системы', 'Главное управление Смоленской области по регулированию контрактной системы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10296, 67, 10295, '', 'Отдел проведения конкурентных способов определения поставщиков (подрядчиков, исполнителей)');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10297, 67, 10295, '', 'Отдел проведения запросов котировок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10298, 67, 10295, '', 'Отдел правового и кадрового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10299, 67, 10295, '', 'Отдел методологического сопровождения деятельности заказчиков и мониторинга закупок');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10300, 67, 10001, 'Главное управление записи актов гражданского состояния Смоленской области', 'Главное управление записи актов гражданского состояния Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10301, 67, 10300, '', 'Отдел правовой и контрольно-аналитической работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10302, 67, 10300, '', 'Отдел накопления, хранения и выдачи документов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10303, 67, 10300, '', 'Отдел бухгалтерского учета, отчетности и планирования расходов');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10304, 67, 10300, '', 'Отдел кадровой и организационной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10305, 67, 10300, '', 'Отдел информатизации');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10306, 67, 10001, 'Главное управление «Государственная жилищная инспекция Смоленской области»', 'Главное управление «Государственная жилищная инспекция Смоленской области»');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10307, 67, 10306, '', 'Инспекторский отдел');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10308, 67, 10306, '', 'Отдел капитального ремонта');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10309, 67, 10306, '', 'Отдел лицензирования и надзора за выбором способа управления');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10310, 67, 10306, '', 'Отдел контроля обоснованности платы за ЖКУ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10311, 67, 10306, '', 'Сектор административного производства и правовой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10312, 67, 10306, '', 'Отдел сопровождения информационных систем и организационной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10313, 67, 10306, '', 'Сектор бухгалтерской и кадровой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10314, 67, 10001, 'Главное управление ветеринарии Смоленской области', 'Главное управление ветеринарии Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10315, 67, 10314, '', 'Отдел противоэпизоотических мероприятий');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10316, 67, 10314, '', 'Отдел ветеринарии');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10317, 67, 10314, '', 'Отдел бухгалтерского учета, отчетности и материального обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10318, 67, 10314, '', 'Отдел организационно-правовой и кадровой работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10319, 67, 10001, 'Главное управление Смоленской области по обеспечению деятельности противопожарно-спасательной службы', 'Главное управление Смоленской области по обеспечению деятельности противопожарно-спасательной службы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10320, 67, 10319, '', 'Отдел кадрового и финансового обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10321, 67, 10319, '', 'Отдел по обеспечению мероприятий гражданской защиты');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10322, 67, 10319, '', 'Отдел по обеспечению деятельности противопожарно-спасательной службы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10323, 67, 10001, 'Главное управление Смоленской области по делам молодежи и гражданско-патриотическому воспитанию', 'Главное управление Смоленской области по делам молодежи и гражданско-патриотическому воспитанию');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10324, 67, 10323, '', 'Отдел правовой, кадровой работы, финансового и организационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10325, 67, 10323, '', 'Отдел разработки и реализации областных государственных программ');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10326, 67, 10323, '', 'Отдел по делам молодежи');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10327, 67, 10323, '', 'Отдел организации гражданско-патриотического воспитания');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10328, 67, 10323, '', 'Отдел мониторинга и информационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10329, 67, 10001, 'Главное управление Смоленской области по культурному наследию', 'Главное управление Смоленской области по культурному наследию');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10330, 67, 10329, '', 'Сектор бухгалтерской и организационной работы');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10331, 67, 10329, '', 'Отдел государственной охраны объектов культурного наследия');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10332, 67, 10329, '', 'Отдел реставрации и государственного учета объектов культурного наследия');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10333, 67, 10001, 'Служба по обеспечению деятельности мировых судей Смоленской области', 'Служба по обеспечению деятельности мировых судей Смоленской области');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10334, 67, 10333, '', 'Отдел правового, материально-технического и информационного обеспечения');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10335, 67, 10333, '', 'Отдел бюджетного учета и администрирования платежей');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10336, 67, 10333, '', 'Отдел кадрового обеспечения и делопроизводства');
INSERT INTO region_divisions(id, region_fk, parent_division_fk, short_name, long_name) VALUES (10337, 67, 10333, '', 'Аппараты мировых судей');